# Generated by Django 5.0.3 on 2024-04-03 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_id', models.IntegerField()),
                ('t_name', models.CharField(max_length=50)),
                ('t_email', models.EmailField(max_length=30)),
                ('t_phone', models.IntegerField()),
                ('t_address', models.CharField(max_length=100)),
            ],
        ),
    ]
