# Generated by Django 5.0.3 on 2024-04-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='id',
        ),
        migrations.AlterField(
            model_name='teachers',
            name='t_address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='t_email',
            field=models.EmailField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='t_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='teachers',
            name='t_phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
