# Generated by Django 5.0.3 on 2024-04-03 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_remove_teachers_id_alter_teachers_t_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='t_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
